---

# Install mysql database on every node
# By default, cuckoo uses sqlite which is not suited for cuckoo distributed
- include_role:
    name: geerlingguy.mysql
  vars:
    mysql_enabled_on_startup: yes
    mysql_databases:
      - name: cuckoo
  become: yes
  become_method: sudo

# Wait for mysql to start
- wait_for:
    port: 3306
    delay: 10
  
- name: Inform cuckoo to use mysql
  become: True
  ini_file:
    dest: '{{ cuckoo_root }}/conf/cuckoo.conf'
    section: 'database'
    option: 'connection'
    value: 'mysql://root:root@localhost/cuckoo'
  notify: restart cuckoo
