---

- name: Generate Cuckoo Sandbox API uWSGI configuration
  command: /usr/local/bin/cuckoo api --uwsgi
  become: yes
  become_user: cuckoo
  register: cuckoo_api_uwsgi

- name: Install Cuckoo Sandbox API uWSGI configuration  
  copy: content="{{ cuckoo_api_uwsgi.stdout }}" dest=/etc/uwsgi/apps-available/cuckoo-api.ini owner=root group=root mode=0644
  become: yes
  become_method: sudo
  notify: restart uwsgi
  
- name: Enable Cuckoo Sandbox API uWSGI Configuration
  become: yes
  become_method: sudo
  file: src=/etc/uwsgi/apps-available/cuckoo-api.ini dest=/etc/uwsgi/apps-enabled/cuckoo-api.ini state=link
  notify: restart uwsgi

- name: Generate Cuckoo Sandbox API NGINX Configuration
  command: /usr/local/bin/cuckoo api -H 0 --nginx
  become: yes
  become_user: cuckoo
  register: cuckoo_api_nginx

- name: Install Cuckoo Sandbox API NGINX Configuration
  copy: content="{{ cuckoo_api_nginx.stdout }}" dest=/etc/nginx/sites-available/cuckoo-api.conf owner=root group=root mode=0644
  become: yes
  become_method: sudo
  notify: restart nginx

- name: Enable Cuckoo Sandbox API NGINX Configuration
  become: yes
  become_method: sudo
  file: src=/etc/nginx/sites-available/cuckoo-api.conf dest=/etc/nginx/sites-enabled/cuckoo-api.conf state=link
  notify: restart nginx
