---

# Install dependencies, download cuckoo, set up user, group, and permissions
- include: install_cuckoo.yml
  become: True
  tags: ['role::cuckoo::install']

# Install nginx and uwsgi if needed
- include: install_nginx_uwsgi.yml
  when: cuckoo_enable_web_interface or cuckoo_enable_api or cuckoo_enable_distributed or cuckoo_management_node
  tags: ['role::cuckoo::install']
  
- block:
  
  # Download, build and install yara from sources
  - include: install_yara.yml
    when: cuckoo_enable_yara
    tags: ['role::cuckoo::install']
  
  # Download and install volatility
  - include: install_volatility.yml
    when: cuckoo_enable_volatility
    tags: ['role::cuckoo::install','role::cuckoo::volatility']
  
  # Set up cuckoo REST API
  - include: configure_nginx_uwsgi.yml command="api -H 0" file=api
    when: cuckoo_enable_api or cuckoo_enable_distributed
    tags: ['role::cuckoo::configure','role::cuckoo::api']
  
  # Set up cuckoo web interface
  - include: configure_nginx_uwsgi.yml command="web" file=web
    when: cuckoo_enable_web_interface
    tags: ['role::cuckoo::configure','role::cuckoo::web']
  
  # If machinary==kvm, install libvirt
  - include: configure_kvm.yml
    when: cuckoo_machinery=="kvm"
    tags: ['role::cuckoo::configure', 'role::cuckoo::kvm']

  # Configure cuckoo
  - include: configure_cuckoo.yml
    tags: ['role::cuckoo::configure']

  # Configure cuckoo rooter
  - include: configure_rooter.yml
    tags: ['role::cuckoo::configure', 'role::cuckoo::rooter']
    when: cuckoo_enable_rooter
    
  when: cuckoo_worker_node

# Set up cuckoo distributed
- include: configure_distributed.yml
  when: cuckoo_enable_distributed
  tags: ['role::cuckoo::configure', 'role::cuckoo::distributed']